name: build

on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  NAMESPACE: swooletw
  IMAGE_NAME: swoole

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        include:
          - php: "8.1"
            swoole: "5.0.3"
          - php: "8.2"
            swoole: "5.0.3"

    name: Build Swoole ${{ matrix.swoole }} (php-${{ matrix.php }})

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}

      - name: Login to GitHub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: dockerfiles/${{ matrix.swoole }}/php${{ matrix.php }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
